// <auto-generated />
namespace ShoppingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renamecustomertorecipient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamecustomertorecipient));
        
        string IMigrationMetadata.Id
        {
            get { return "201702071914358_rename-customer-to-recipient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
